version: '3.8'
name: redis-cluster
services:
  redis-1:
    build: .
    container_name: redis_1
    command: redis-server --protected-mode no --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7001:7001"
    volumes:
      - ./PythonScripts:/PythonScripts
      - ./BashScripts:/BashScripts
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.2
    cap_add:
      - NET_ADMIN

  redis-2:
    build: .
    container_name: redis_2
    command: redis-server --protected-mode no --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7002:7002"
    volumes:
      - ./PythonScripts:/PythonScripts
      - ./BashScripts:/BashScripts
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.3
    cap_add:
      - NET_ADMIN

  redis-3:
    build: .
    container_name: redis_3
    command: redis-server --protected-mode no --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7003:7003"
    volumes:
      - ./PythonScripts:/PythonScripts
      - ./BashScripts:/BashScripts
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.4
    cap_add:
      - NET_ADMIN

  redis-4:
    build: .
    container_name: redis_4
    command: redis-server --protected-mode no --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7004:7004"
    volumes:
      - ./PythonScripts:/PythonScripts
      - ./BashScripts:/BashScripts
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.5
    cap_add:
      - NET_ADMIN

  redis-5:
    build: .
    container_name: redis_5
    command: redis-server --protected-mode no --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7005:7005"
    volumes:
      - ./PythonScripts:/PythonScripts
      - ./BashScripts:/BashScripts
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.6
    cap_add:
      - NET_ADMIN

  redis-6:
    build: .
    container_name: redis_6
    command: redis-server --protected-mode no --port 7006 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7006:7006"
    volumes:
      - ./PythonScripts:/PythonScripts
      - ./BashScripts:/BashScripts
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.7
    cap_add:
      - NET_ADMIN

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
